# Generated by Django 3.1.7 on 2021-04-07 15:24

import apps.user.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210406_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follows',
            options={'ordering': ['-follow'], 'verbose_name': '关注列表', 'verbose_name_plural': '关注列表'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ['-create_time'], 'verbose_name': '用户消息', 'verbose_name_plural': '用户消息'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_image',
            new_name='user_avatar',
        ),
        migrations.RemoveField(
            model_name='follows',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_imag',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='add_time',
        ),
        migrations.AddField(
            model_name='follows',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 7, 15, 24, 14, 61381), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to=apps.user.models.user_directory_path, verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 7, 15, 24, 28, 310242), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follows',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=20, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='has_read',
            field=models.BooleanField(default=False, verbose_name='已读'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='is_supper',
            field=models.BooleanField(default=False, verbose_name='系统消息'),
        ),
    ]
