# Generated by Django 3.1.7 on 2021-04-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210407_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_avatar',
        ),
    ]
