# Generated by Django 3.1.7 on 2021-04-15 17:49

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=apps.user.models.user_directory_path, verbose_name='用户头像'),
        ),
    ]
