# Generated by Django 3.1.7 on 2021-04-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210415_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
