# Generated by Django 3.1.7 on 2021-04-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210419_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_comment',
            old_name='comments',
            new_name='content',
        ),
    ]
