# Generated by Django 3.1.7 on 2021-04-26 18:34

import apps.forum.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0020_forum_is_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-create_time',), 'verbose_name': '帖子评论表', 'verbose_name_plural': '帖子评论表'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ('-create_time',), 'verbose_name': '帖子表', 'verbose_name_plural': '帖子表'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='forums',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='is_type',
            new_name='can_view',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='forum_click',
            old_name='forums',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='parent_comment',
            old_name='comments',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='parent_comment',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='parent_comment',
            old_name='forums',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='parent_comment',
            old_name='parent_comments',
            new_name='parent_comment',
        ),
        migrations.RenameField(
            model_name='parent_comment',
            old_name='to_Parent_Comments',
            new_name='to_Parent_Comment',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.CreateModel(
            name='Forum_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='板块名称')),
                ('image', models.ImageField(blank=True, upload_to=apps.forum.models.forum_template_path, verbose_name='图标')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '论坛版块',
                'verbose_name_plural': '论坛版块',
                'ordering': ('-create_time',),
            },
        ),
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum_template', verbose_name='板块名称'),
        ),
        migrations.DeleteModel(
            name='Forum_plate',
        ),
    ]
